"""
Core data models for the All-Weather Multi-Market AI Panel.

This module defines the fundamental data structures that flow through every layer
of the system — from raw market ticks to AI-generated factor signals.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# ============================================================
# Market Data Models
# ============================================================


class MarketType(str, Enum):
    POLYMARKET = "polymarket"
    BINANCE = "binance"
    CUSTOM = "custom"


class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"


@dataclass(frozen=True, slots=True)
class OrderBookLevel:
    price: float
    size: float


@dataclass(slots=True)
class OrderBookSnapshot:
    """L2 order book snapshot at a point in time."""

    market_id: str
    timestamp_ms: int
    bids: list[OrderBookLevel]  # sorted descending by price
    asks: list[OrderBookLevel]  # sorted ascending by price

    @property
    def mid_price(self) -> float:
        if self.bids and self.asks:
            return (self.bids[0].price + self.asks[0].price) / 2
        return 0.0

    @property
    def spread(self) -> float:
        if self.bids and self.asks:
            return self.asks[0].price - self.bids[0].price
        return float("inf")

    @property
    def bid_depth(self) -> float:
        return sum(level.size for level in self.bids)

    @property
    def ask_depth(self) -> float:
        return sum(level.size for level in self.asks)


@dataclass(frozen=True, slots=True)
class Trade:
    market_id: str
    timestamp_ms: int
    price: float
    size: float
    side: Side


@dataclass(slots=True)
class Tick:
    """A unified market tick combining price, volume, and book data."""

    market_id: str
    timestamp_ms: int
    mid_price: float
    last_trade_price: float
    volume_24h: float
    spread: float
    bid_depth: float
    ask_depth: float
    book_imbalance: float  # (bid_depth - ask_depth) / (bid_depth + ask_depth)

    @classmethod
    def from_book_and_trades(
        cls, book: OrderBookSnapshot, recent_trades: list[Trade], volume_24h: float
    ) -> Tick:
        total_depth = book.bid_depth + book.ask_depth
        imbalance = (book.bid_depth - book.ask_depth) / total_depth if total_depth > 0 else 0.0
        last_price = recent_trades[-1].price if recent_trades else book.mid_price
        return cls(
            market_id=book.market_id,
            timestamp_ms=book.timestamp_ms,
            mid_price=book.mid_price,
            last_trade_price=last_price,
            volume_24h=volume_24h,
            spread=book.spread,
            bid_depth=book.bid_depth,
            ask_depth=book.ask_depth,
            book_imbalance=imbalance,
        )


# ============================================================
# Factor Models
# ============================================================


class FactorStatus(str, Enum):
    CANDIDATE = "candidate"  # just generated by AI, not yet tested
    SANDBOX = "sandbox"  # undergoing backtest in sandbox
    GREY = "grey"  # passed sandbox, in live grey-scale test with low weight
    ACTIVE = "active"  # fully active in production
    DECAYING = "decaying"  # IC dropping, under observation
    RETIRED = "retired"  # removed from production


@dataclass(slots=True)
class FactorValue:
    """A single factor's output at a point in time."""

    factor_id: str
    market_id: str
    timestamp_ms: int
    value: float  # normalized to [-1, 1]
    weight: float  # current dynamic weight assigned by RL/AI
    ic_rolling: float  # rolling information coefficient
    status: FactorStatus


@dataclass(slots=True)
class FactorDefinition:
    """Describes a factor — either human-coded or AI-generated."""

    factor_id: str
    name: str
    description: str
    expression: str  # e.g., "rank(ts_corr(order_book_imbalance, ts_mean(volume_ratio, 10), 20))"
    author: str  # "human" or "ai_agent"
    created_at_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    status: FactorStatus = FactorStatus.CANDIDATE
    initial_weight: float = 0.01
    metadata: dict[str, Any] = field(default_factory=dict)


# ============================================================
# Signal & Position Models
# ============================================================


@dataclass(slots=True)
class CompositeSignal:
    """Aggregated signal from all active factors for a single market."""

    market_id: str
    timestamp_ms: int
    raw_score: float  # weighted sum of factor values
    normalized_score: float  # mapped to [-1, 1]
    confidence: float  # 0 to 1
    active_factor_count: int
    factor_contributions: dict[str, float]  # factor_id -> contribution


@dataclass(slots=True)
class Position:
    market_id: str
    side: Side
    size: float
    entry_price: float
    current_price: float
    unrealized_pnl: float
    timestamp_ms: int


# ============================================================
# AI Agent Models
# ============================================================


class AgentAction(str, Enum):
    GENERATE_FACTOR = "generate_factor"
    RETIRE_FACTOR = "retire_factor"
    ADJUST_WEIGHT = "adjust_weight"
    CIRCUIT_BREAK = "circuit_break"
    RESUME_MARKET = "resume_market"
    LOG_INSIGHT = "log_insight"


@dataclass(slots=True)
class AgentDecision:
    """A decision made by the AI agent, logged for transparency."""

    action: AgentAction
    market_id: str
    timestamp_ms: int
    reasoning: str  # natural language explanation
    details: dict[str, Any] = field(default_factory=dict)


# ============================================================
# Regime & Risk Models
# ============================================================


class MarketRegime(str, Enum):
    NORMAL = "normal"
    HIGH_VOLATILITY = "high_volatility"
    LOW_LIQUIDITY = "low_liquidity"
    TRENDING = "trending"
    MEAN_REVERTING = "mean_reverting"
    CRISIS = "crisis"


@dataclass(slots=True)
class RegimeState:
    market_id: str
    timestamp_ms: int
    regime: MarketRegime
    confidence: float
    volatility_z: float  # z-score of current volatility vs historical
    liquidity_z: float  # z-score of current liquidity vs historical


@dataclass(slots=True)
class RiskSnapshot:
    """Global and per-market risk state at a point in time."""

    timestamp_ms: int
    total_equity: float
    total_pnl: float
    max_drawdown_pct: float
    market_risks: dict[str, MarketRisk] = field(default_factory=dict)
    circuit_breakers_active: list[str] = field(default_factory=list)


@dataclass(slots=True)
class MarketRisk:
    market_id: str
    drawdown_pct: float
    regime: MarketRegime
    position_value: float
    slippage_estimate_bps: float
    is_circuit_broken: bool = False
